name: CI/CD for React App

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code (local)
              uses: actions/checkout@v3

            - name: SSH and Deploy to EC2
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: 22
                  script: |
                      # Navigate to the actual app directory
                      cd /home/ubuntu/react-app

                      # Pull the latest code
                      git pull origin main

                      # Stop and remove existing container if any
                      sudo docker stop react-app || true
                      sudo docker rm react-app || true

                      # Build Docker image (Dockerfile should be present here)
                      sudo docker build -t react-app:latest .

                      # Run the new container
                      sudo docker run -d \
                        --name react-app \
                        -p 80:80 \
                        react-app:latest
