name: CI/CD for React App

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code (local)
              uses: actions/checkout@v3

            - name: SSH and Deploy to EC2
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: 22
                  script: |
                      # Go to the app directory
                      cd /react-app

                      # Pull latest changes
                      git pull origin main

                      # Stop and remove the old container if exists
                      sudo docker stop react-app || true
                      sudo docker rm react-app || true

                      # Build Docker image (assumes Dockerfile exists here)
                      sudo docker build -t react-app:latest .

                      # Run the container on port 80
                      sudo docker run -d \
                        --name react-app \
                        -p 80:80 \
                        react-app:latest
